repos:
  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    rev: v0.3
    hooks:
      - id: circleci_validate
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        files: ^src/
