version: 2.1

orbs: 
  gcp-cli: circleci/gcp-cli@2.4.0
  helm: circleci/helm@1.2.0
  kubernetes: circleci/kubernetes@1.0.2
  docker: circleci/docker@2.0.1

workflows:
  ci-cd:  
    jobs:
      - docker-lint:
          context: moonwalkers
      - npm-test: 
          context: moonwalkers
          requires:
            - docker-lint
      - build-and-push-docker-image:
          context: moonwalkers
          requires:
            - npm-test
      - push-helm-chart:
          context: moonwalkers
          requires: 
            - build-and-push-docker-image
      - deploy-helm-chart:
          context: moonwalkers
          requires:
            - push-helm-chart
      - validate-app-is-running:
          context: moonwalkers
          requires:
            - deploy-helm-chart

commands:
  install-gcp-cli:
    steps:
      - gcp-cli/install:
          version: 366.0.0
      - gcp-cli/initialize:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-compute-region: GCLOUD_COMPUTE_REGION
          google-compute-zone: GCLOUD_COMPUTE_ZONE
          google-project-id: GCLOUD_PROJECT_ID
  configure-artifact-registry:
    steps:
      - run:
          name: Configure Artifact Registry
          command: |
            gcloud auth configure-docker us-east1-docker.pkg.dev
  connect-to-gke-cluster:
    steps:
      - run:
          name: Connect to GKE cluster
          command: |
            gcloud container clusters get-credentials gke-ycit021-devops-project --region us-east1

jobs:
  docker-lint:
    executor: docker/hadolint
    steps:
      - checkout
      - docker/hadolint
  npm-test:
    docker: 
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run:
          name: npm install
          command: | 
            npm install
      - run:
          name: npm test
          command: |
            npm test
      - run:
          name: npm run lint
          command: |
            npm run lint
      - run:
          name: npm run prettier:check
          command: |
            npm run prettier:check
  build-and-push-docker-image:
    docker: 
      - image: cimg/base:2021.11
    steps:
      - checkout
      - setup_remote_docker
      - install-gcp-cli
      - configure-artifact-registry
      - run:
          name: Build Docker image
          command: |
            docker build -t realworld-app .
      - run:
          name: Tag and Push Docker image
          command: |
            docker tag realworld-app ${GCP_REGISTRY_PATH}/realworld-app:${CIRCLE_SHA1}
            docker tag ${GCP_REGISTRY_PATH}/realworld-app:${CIRCLE_SHA1} ${GCP_REGISTRY_PATH}/realworld-app:latest
            docker push ${GCP_REGISTRY_PATH}/realworld-app:${CIRCLE_SHA1}
            docker push ${GCP_REGISTRY_PATH}/realworld-app:latest
  push-helm-chart:
    docker: 
      - image: cimg/base:2021.11
    steps:
      - checkout
      - install-gcp-cli
      - helm/install-helm-client:
          version: "v3.7.2"
      - configure-artifact-registry
      - run:
          name: Package and push Helm chart
          command: |
            export HELM_EXPERIMENTAL_OCI=1
            echo $GCLOUD_SERVICE_KEY > $HOME/gcloud.json
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
            gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://us-east1-docker.pkg.dev
            helm package realworld/
            helm push realworld-0.1.0.tgz oci://us-east1-docker.pkg.dev/devops-practices-and-tools/realworld-helm
  deploy-helm-chart:
    docker:
      - image: cimg/base:2021.11
    steps:
      - install-gcp-cli
      - connect-to-gke-cluster
      - helm/install-helm-client:
          version: "v3.7.2"
      - kubernetes/install
      - run:
          name: Deploy new helm chart
          command: |
            export HELM_EXPERIMENTAL_OCI=1
            echo $GCLOUD_SERVICE_KEY > $HOME/gcloud.json
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
            gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://us-east1-docker.pkg.dev
            helm upgrade --install realworld oci://us-east1-docker.pkg.dev/devops-practices-and-tools/realworld-helm/realworld --version 0.1.0
            sleep 60
          # TODO: Automate sleep - check when the app is up
  validate-app-is-running:
    docker:
      - image: cimg/base:2021.11
    steps:
      - install-gcp-cli
      - connect-to-gke-cluster
      - kubernetes/install
      - run:
          name: Validate pod is running
          command: |
            kubectl get pods
      - run:
          name: Validate URL is reachable
          command: |
            export SERVICE_IP=$(kubectl get svc --namespace default realworld --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
            echo http://$SERVICE_IP:3000
            curl --connect-timeout 30 http://$SERVICE_IP:3000